apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: helloworld
  namespace: camel-k
spec:
  flows:
    - from:
        steps:
        - setBody:
            simple: Hello Camel from ${routeId}
        - log: ${body}
        uri: timer:yaml