apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bulk-storage-provisioner
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bulk-storage-provisioner
subjects:
  - kind: ServiceAccount
    name: bulk-storage-provisioner
    namespace: bulk-storage
