# Generated by Django 5.2.6 on 2025-09-23 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6721683e-26ce-4e19-887d-fb98031864c9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
