# Generated by Django 5.2.17 on 2026-10-01 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
